### ISSUE TITLE
Show screen instantly

### ISSUE THREAD

**Issue by s00500** [lubeda/EspHoMaTriXv2#112]
# Question

Hey, cool project,
Is there a way to show something immediatly ? I tried creating a screen then force screen but this will wait until the current screens time is out before switching... anyway to stop that ?

Also having only minute steps for lifetime will mean when I want to show a message for 10 seconds and then remove the screen it will come up once more...

Is there anything I am doing wrong ? How would I best approach such a problem ?

Greetings
Lukas

## Additional information
Using Ulanzi Display

**Comment by andrewjswan** [comment]
2023.9.1: `alert_screen` - show the specified icon with text, screen forced and lifetime = screen_time

**Comment by lubeda** [comment]
and force_screen may be used

**Comment by s00500** [comment]
Awesome, works as expected
