### ISSUE TITLE
[FEATURE REQUEST] Allow rainbow alerts

### ISSUE THREAD

**Issue by sti0** [lubeda/EspHoMaTriXv2#175]
# Feature Request

### Is your feature request related to a problem?

Currently the `alert_screen` service can only be called with RGB color. It would be nice if a rainbow option (or new service) could be added like it already exists for `icon_screen` etc.

### Describe the solution / feature you'd like

Add a new service `rainbow_alert_screen` which then shows the text in rainbow colors.

### Describe alternatives you've considered

Extend the existing service `alert_screen` but this wouldn't match the existing behavior of the other services.

**Comment by andrewjswan** [comment]
Added in https://github.com/lubeda/EspHoMaTriXv2/pull/176
