### ISSUE TITLE
[QUESTION] How do I add 1 hour to the time displayed?

### ISSUE THREAD

**Issue by robgardien** [lubeda/EspHoMaTriXv2#211]
# Question

I would like to adjust the timezone to UTC + 1, how can I achieve this?

## Additional information

- used Hardware:
  - ESP32 or ESP8266: Ulanzi TC001
  - EspHoMaTriXv2 version: 2023.12.7

**Comment by andrewjswan** [comment]
Is this your current TZ, or do you want to register a different one? If different, then according to the documentation:
https://esphome.io/components/time/index.html

if current:
```
ESPHome tries to automatically infer the time zone string based on the time zone of the computer that is running ESPHome, but this might not always be accurate.
```

**Comment by lubeda** [comment]
this issue is not direct related to ehmtx so => close
