### ISSUE TITLE
[QUESTION] After Flashing Ulanzi Making a Tone

### ISSUE THREAD

**Issue by StarScream159** [lubeda/EspHoMaTriXv2#216]
# Question

After flashing the Ulanzi the device is making a constant beep/tone. I've tried rebooting it & flashing it again. It's still making the tone. As soon as I flash my backed up default Ulanzi firmware the beep/tone goes away.

## Additional information

- Ulanzi TC001
- EspHoMaTriXv2 version: "main" (I also tried 2024.1.0 tagged)
- ESPhome 2024.2.0

**Comment by andrewjswan** [comment]
Look maybe help - https://github.com/lubeda/EspHoMaTriXv2/issues/212

**Comment by StarScream159** [comment]
Thank you! I was searching everything except buzzer. "Tone", "beep", "sound" lol. Thanks.
