### ISSUE TITLE
[QUESTION] move the second digit in the calendar one row to the left

### ISSUE THREAD

**Issue by robotm-team** [lubeda/EspHoMaTriXv2#221]
# Question

Hi.

Thank you very much for your work put into this project!

I am wondering if it is possible to move the second digit in the calendar one row to the left.

Something like the picture below (I know, I have mastered paint to perfection ... :-) ).

## Additional information

- used Hardware:
  - ESP32

  - EspHoMaTriXv2 version: 2024.3.0

## Logs

```text
I think it is not necessary.
```

## Additional context

![Bez nazwy](https://github.com/lubeda/EspHoMaTriXv2/assets/76626315/a33399c7-9c2a-4d71-8bd2-37dcc13bc8ac)

**Comment by andrewjswan** [comment]
```
        id(rgb8x32)->expand_icon_to_9(3);
        id(rgb8x32)->icon_clock("calendar|day#2", 1440, 10, true);
        id(rgb8x32)->icon_date("calendar|weekday#2", 1440, 5, true);
```

**Comment by robotm-team** [comment]
Problem solved by @andrewjswan
