### ISSUE TITLE
[QUESTION] I have build the LED for my self but it shows artifacts at start with power

### ISSUE THREAD

**Issue by robudus** [lubeda/EspHoMaTriXv2#232]
# Question

Hi,
i have built the LED with ESP32-Wroom and the LED Matrix 8x32 from Ali. It works great with WLED. AWTrix works great eather.
With blueforcer awtrix-light i have to change the matrix type to matrix:1. How can i get yours to work?
My matrix displays meaningless characters if i power it. I have added pictures.
I have tried the three pixelmapers. type 1-3 but it doesnt work.
Have you a hint for me?

Thanks.

G ROBudus

## Additional information

- used Hardware:
  - ESP32 or ESP8266

  - EspHoMaTriXv2 version: [e.g. 2023.5.0]
![IMG_8990](https://github.com/lubeda/EspHoMaTriXv2/assets/41438901/b3cd201a-61a7-41c8-a313-add813d9d3d5)
![IMG_8989](https://github.com/lubeda/EspHoMaTriXv2/assets/41438901/3f580719-93b1-4667-b37d-cbbae9674f23)

## Logs

```text
(optional) Add relevant logs which could help tackle the problem.
```

**Comment by lubeda** [comment]
Hi,
this is not a question for ehmtx, it's more a question for esp home. The easiest way ist to recode the pixelmaper Tape-1 from awtrix and code it into esphome style.
