### ISSUE TITLE
[QUESTION] 8x8 Matrix Support

### ISSUE THREAD

**Issue by ataa** [lubeda/EspHoMaTriXv2#243]
# Question

Hello,

Is it possible to use ESP32-S3 Modules with 8x8 matrix and display an icon like weather icon first, then scroll the text?

I am using ESP32-S3-Matrix (8x8 addressable RGB + Gyro & Acc. Sensor) which can be bought for about $7.

![ESP32-S3-Matrix_func](https://github.com/user-attachments/assets/145c08ca-04f8-42fa-a7e7-7037d514a4bb)

**Comment by andrewjswan** [comment]
The current firmware should work fine with this type of matrix, with all the limitations that 8x8 imposes on the algorithm designed for 8x32. 
You can also rewrite the firmware purely for 8x8, and remove the extra ones (screens that only support 8x32).
But it is better to add 3 8x8 matrices and get 8x32.

**Comment by lubeda** [comment]
8x8 is to small to display readable text.
