### ISSUE TITLE
[FEATURE REQUEST] Clock / Date icon

### ISSUE THREAD

**Issue by MiguelAngelLV** [lubeda/EspHoMaTriXv2#249]
# Feature Request

### Describe the solution / feature you'd like
Allow adding icons for clock and date screens.
Weekday indicator should be reduced (or removed).

**Comment by MiguelAngelLV** [comment]
Sorry, I did not find it...

**Comment by lubeda** [comment]
The latest branch has this option called `show_dow`

**Comment by MiguelAngelLV** [comment]
Yes, I found it after open the issue
