### ISSUE TITLE
Hyphen in device name an issue?

### ISSUE THREAD

**Issue by davlaw** [lubeda/EspHoMaTriXv2#31]
Just dealt with an issue with a device that had a hyphen/dash in the device name.

Was not calling correct service in HA services due to conflict

**Comment by lubeda** [comment]
Hi, the service part does not belong to my component. So you have to make the issue in the esphome repo! But without any log file or further detail nobody can help you

**Comment by lubeda** [comment]
By the way, I use hyphen on my development display without any problem.

**Comment by davlaw** [comment]
appreciate the help
