### ISSUE TITLE
[FEATURE REQUEST] RTL: set RTL per screen or new modes per screen

### ISSUE THREAD

**Issue by lubeda** [lubeda/EspHoMaTriXv2#39]
@idodov

**Comment by lubeda** [comment]
I don't want to add another parameter to the default service cal because there are already plenty of parameters. But new modes/service calls for RTL seem possible.

**Comment by idodov** [comment]
It can be a boolean parameter like '''default font''' in the service. Adding that would be awesome.

**Comment by idodov** [comment]
Feel free to explore how I addressed the RTL language display issue on the provided GitHub link: https://github.com/idodov/bidi
If you find the solution helpful, consider adding it to the wiki section.

**Comment by lubeda** [comment]
Hi, i can't test but i added a wiki page. Hope it helps

**Comment by idodov** [comment]
You might also be interested in another feature I have that allows album art to be displayed as icons. 
https://github.com/idodov/LedMatrixAlbumArt

**Comment by ofirsnb** [comment]
Idodov,   very nice idea of the `LedMatrixAlbumArt`, thanks for sharing:)

Also thank you Lubeda and Andrew of course,  I know you've been looking for a solution for this FR and similar cases.

I myself,  using a lot of both Heb+Eng strings for different scenarios,  
and an option to allow setting RTL per screen would be super helpful and appreciated! 🙏 

As far as I know too,  unfortunately,  we can't use optionals in the ESPHome service-calls,  so I understand the hesitation,
but may I suggest a middle-ground solution?  
Can we have an option,  to set the `rtl` flag per `default_font` and `special_font` (or even just for `special_font`)?
Something like:
```
ehmtxv2:
  id: rgb8x32
  default_font_id: ehmtx_font
  special_font_id: ehmtx_font_heb
  special_font_rtl: true  # default will be `false`
```
That way,   anytime we select the `special_font` using the current service-calls,  it will render with RTL.

I think this solution will be most suitable considering the current limitations,  and doesn't break any current usages.

What do you think?

**Comment by lubeda** [comment]
i cant support rtl
