### ISSUE TITLE
scroll_small_text: false does not work

### ISSUE THREAD

**Issue by andrew-codechimp** [lubeda/EspHoMaTriXv2#47]
# Bug report

## Describe the bug
The flag scroll_small_text does not work correctly.  Setting it to false small text still scrolls

## Additional information
I attempted to fix it as did @joncar, see links below but neither quite get's it right

https://github.com/andrew-codechimp/EspHoMaTriXv2/commit/bdf69aa729a1d1a2e3ab9fe948002dd730f2b987
https://github.com/joncar/EspHoMaTriXv2/tree/user/joncar/01-fix-scroll

- used Hardware:
  - ESP32
  - EspHoMaTriXv2 version: [e.g. 2023.6.5]

## To Reproduce

Set scroll_small_text: false and add a screen with small text

## Expected behavior

Small text will not scroll when set to false

## Configuration

```text
(optional) The YAML you used in epshome without any password
```

## Logs

```text
(optional) Add relevant logs which could help tackle the problem.
```

## Services calls

```text
(optional) The YAML of your service calls
```

**Comment by andrew-codechimp** [comment]
I tried it but it's inverted, setting scroll_small_text: false still scrolled small text, you have to set it to true not to scroll.

**Comment by joncar** [comment]
I don't see how. Strange. I just tested `scroll_small_text: true`, `scroll_small_text: false`, and with `scroll_small_text` unspecified and all behaved how I expected.

**Comment by joncar** [comment]
Any chance your edit to `EHMTX_queue.cpp` was still in your esphome code when you tested? That would invert the flag.

**Comment by andrew-codechimp** [comment]
Yes, I did leave my edit in EHMT_queue.cpp, which I didn't think I did, so I'm an idiot :)  Blame it on early morning tinkering.

Are you going to submit a PR with your fix?

**Comment by joncar** [comment]
Yup, I'll submit the PR to fix this issue.

**Comment by lubeda** [comment]
merged in main. Thanx for the support!
