### ISSUE TITLE
[BUG] Blueprints not working

### ISSUE THREAD

**Issue by fbradyirl** [lubeda/EspHoMaTriXv2#8]
# Bug report

Thanks for this repo but the Blueprints I’ve tried all show me this error.

![image](https://user-images.githubusercontent.com/254309/236697531-8dc069ae-ff85-4208-b678-35e37911a13f.jpeg)

![image](https://user-images.githubusercontent.com/254309/236697540-1cad91f9-0825-4fa0-9ce8-d8a92e9ae7be.jpeg)

## Additional information

- used Hardware:
  - ESP32
  - EspHoMaTriXv2 version: latest master code from 7 May 2023

## Configuration

```text
(optional) The YAML you used in epshome without any password
```

## Logs

```text
(optional) Add relevant logs which could help tackle the problem.
```

## Services calls

```text
(optional) The YAML of your service calls
```

**Comment by lubeda** [comment]
I will investigate

**Comment by lubeda** [comment]
Hi, please try this version: https://github.com/lubeda/EspHoMaTriXv2/blob/develop/copy2esphome/EHMTX_easy_state.yaml

**Comment by fbradyirl** [comment]
Yes this works thank you. I think the issue is with all the other blueprints also.

**Comment by lubeda** [comment]
I will check, but not today.

**Comment by fbradyirl** [comment]
No problem thanks for sorting this.
