### ISSUE TITLE
[FEATURE REQUEST] Add a screen with an icon and a time with the day of the week.

### ISSUE THREAD

**Issue by malinovsku** [lubeda/EspHoMaTriXv2#85]
# Feature Request

### Describe the solution / feature you'd like

It would be great if you added an additional display option similar to icon_screen, but instead of text that would display the time and day of the week. The name of the new function could be selected icon_time,
parameters to run: "icon_name", "lifetime", "screen_time", "default_font", "r", "g", "b"

### Additional context

As an example of a screens, displaying the weather and time icons with the day of the week.
![Снимок экрана 2023-09-20 в 22 05 13](https://github.com/lubeda/EspHoMaTriXv2/assets/34610364/74255f23-c267-40db-b24d-ada38a941faf)

**Comment by andrewjswan** [comment]
Interesting idea as an additional time display screen, or as an alternate screen with getting the weather from the HA.

**Comment by lubeda** [comment]
It's implemented in 2023.8.0. Can you please give me an example for the wiki?

**Comment by lubeda** [comment]
https://github.com/lubeda/EspHoMaTriXv2/wiki/icon-clock

**Comment by malinovsku** [comment]
@lubeda thank you, the display is the right one, but the icon moves two columns to the right, while everything is as it should be in icon_screen, as I understood it in the [code](https://github.com/lubeda/EspHoMaTriXv2/blob/2023.8.0/components/ehmtxv2/EHMTX_queue.cpp#L343), but it would be better if the icon starts from the very edge without indentation and the clock is shifted to the middle of the remaining one, since when changing displays with icons, they are like they would jump because of the difference in boundaries.
![1](https://github.com/lubeda/EspHoMaTriXv2/assets/34610364/19e552da-e5a3-444f-a4bc-a3483074351c)

**Comment by lubeda** [comment]
Upps, i will fix this.

**Comment by malinovsku** [comment]
@lubeda after a couple of days of using this display, I realized that there are not enough variations of icons with hours and days of the week, so that they could be created in the same amount as, for example, icon_screen and deleted by the del_screen service. as an example of usage, display both a calendar icon with a clock and a weather icon with a clock.
There may be a conflict when deleting, and https://github.com/lubeda/EspHoMaTriXv2/issues/83 it would help in solving this issue, to delete by screen id

**Comment by andrewjswan** [comment]
Interesting idea, it can be well developed, for example to output date with hours, or date with day of week and year, etc.
For example, for the date, we take the backing icon `calendar`
![image](https://github.com/lubeda/EspHoMaTriXv2/assets/3609660/83ffcebe-34da-4d06-a074-f34a36463890)
And on top of that, display the current date:
![image](https://github.com/lubeda/EspHoMaTriXv2/assets/3609660/94dd4c0e-9fc6-4c6c-ba6f-2c993668cd28)
And next to it we can display either time or date, also we can display the current day of the week:
![image](https://github.com/lubeda/EspHoMaTriXv2/assets/3609660/c3ef86a5-7818-4aed-b4e2-1b1f3501575a) ![image](https://github.com/lubeda/EspHoMaTriXv2/assets/3609660/55380f44-2e3a-4ede-85de-2bf5306882b9)

And we can rooluchat let's say such a variant of the screen (here you can even safely use the crawl line).
![image](https://github.com/lubeda/EspHoMaTriXv2/assets/3609660/8fbcac1b-f9ff-487d-87b1-d4be29728e6c)
Or this one:
![image](https://github.com/lubeda/EspHoMaTriXv2/assets/3609660/04d04c0c-dbab-4915-b827-26f86900e796)
![image](https://github.com/lubeda/EspHoMaTriXv2/assets/3609660/aab5be12-f845-4d26-9fb2-aa1d913b0b3c)

**Comment by andrewjswan** [comment]
Since we come to an increase of screens with the same information, e.g. Clock, Icon with Clock, Date, Icon with Date, it would be nice to give the possibility to define a starting set of screens in EspHoMaTriXv2 configuration  (if not specified, the default is time, date), for example:
```
emhtx:
  screens:
    - icon_time
    - icon_date
```

Also immediately add localized abbreviations to display the current day of the week (if not specified, the default is English):
```
emhtx:
  week_days:
    - ПН
    - ВТ
    - СР
    - ЧТ
    - ПТ
    - СБ
    - ВС
```
That would solve the problem  https://github.com/lubeda/EspHoMaTriXv2/issues/89

**Comment by andrewjswan** [comment]
On the concept of outputting an icon and text on top of it, it is necessary to think through a convenient mechanism for specifying what to output, let's say type, value, for example:
- weather, *
- calendar, day
- calendar, week_day

**Comment by malinovsku** [comment]
> Upps, i will fix this.

I updated the firmware, and the icon is now in the right place, thank you, but the days of the week are not in the middle at the bottom, 3 indent on the left, and 1 indent on the right.
![Снимок экрана 2023-09-28 в 20 27 09](https://github.com/lubeda/EspHoMaTriXv2/assets/34610364/74e615a6-f195-47d6-9e63-b615e2759c36)

**Comment by lubeda** [comment]
Hopefully finally fixed. @malinovsku Please check again

**Comment by malinovsku** [comment]
@lubeda everything is great now, thank you!
